### ISSUE TITLE
Can't get redirect to work

### ISSUE THREAD

**Issue by allenbargi** [lwsjs/redirect#1]
this is the command I'm usig: 

```shell
ws --stack redirect compress static  --port 5000 --http2 --redirect 'http -> https' --compress --open
```

If I remove redirect it'll work

```shell
ws --stack compress static  --port 5000 --http2 --compress --open
```

I'm not getting any error though. it just shows me a an empty page. 

I've installed these packages globally
```shell
npm install -g local-web-server
npm install -g lws-redirect
```

**Comment by 75lb** [comment]
does it work if you install lws-redirect locally? 

Actually, I think i have spotted an issue - the [`next output`](https://github.com/lwsjs/redirect/blob/master/index.js#L31) should be returned or awaited.. let me test that..

**Comment by 75lb** [comment]
I released a fix in lws-redirect v1.0.4.. please reinstall lws-redirect and try again..

**Comment by allenbargi** [comment]
Still does not work. 
I tried with a local installation and it did not work too.

here's my package json
```json
{
  "name": "build-docs",
  "private": true,
  "scripts": {
    "serve": "ws --stack redirect compress static  --port 5000 --http2 --redirect 'http -> https' --compress --directory out --open"
 },
  "devDependencies": {
    "local-web-server": "^3.0.3",
    "lws-redirect": "^1.0.4",
  }
}
```

I have a single `index.html` in `out` directory. that's all I have in my test repo.

**Comment by 75lb** [comment]
It fails how? And which request URL is failing? If you are trying to redirect HTTP to HTTPs you need **two** servers running, because HTTP and HTTPS run on two different ports.. 

The command in your `npm serve` script is wrong. You are launching an HTTP2 server, therefore only accepting `https://` requests. Your redirect rule will match the `http` in `https://` and redirect to `httpss://`.

You need to run two servers with the correct ports. This is your server catching HTTP (port 80) requests. It will redirect to HTTPS (a separate server on port 443).

```
$ ws --stack redirect  --port 80 --redirect 'http -> https'
```

Here's your main HTTPS server.

```
$ ws --stack compress static  --port 443 --http2 --compress --directory out --open
```

**Comment by 75lb** [comment]
New tutorial, maybe it will help. 

[How to redirect all HTTP traffic to HTTPS](https://github.com/lwsjs/local-web-server/wiki/How-to-redirect-HTTP-traffic-to-HTTPS).
